/* GENERA LOS SCRIPTS PARA PARTICIONES*/
/* SE NECEISTA ENCENDER EL DMBS_OUTPUT */
/* CAMBIAR EL MES!! */

select  
'exec ADMINDB.crea_particiones(''' || TABLE_OWNER || ''',''' || TABLE_NAME || ''',''' || TABLESPACE_PREFIX || ''',''MAR23'',''' || PARTITION_TYPE || ''',''' || TABLESPACE_TYPE || ''');'
from ADMINDB.PARTITION_INFO




/* errores en TC */

BO_CBR_DAT_2023
BO_CBU_DAT_2023
CLE_LC_DAT_2023
CLE_LP_DAT_2023
TC_TDSIH_DAT_2023
BO_NDE_DAT_2023
CLE_EP_DAT_2023
TC_TMF_DAT_ABR23
CLE_ESPRO_DAT_2023
TC_TMFH_DAT_2023
PT_PCH_DAT_2023
TC_TCH_DAT_2023
--BO.CM_LIQUIDACION_DETALLE

CBS
CC.CC_ESTADO_CUENTA_MASIVO_DETA
PR.PR_MOVIMIENTOS
CC_DAT_CECM_ABR23
CC.CC_ESTADO_CUENTA_CKIMAGEN
WC_WPT_DAT_ABR23
CC_DAT_CECM_ABR23
