-- revisa objetos descompilados en CBS

select
   'ALTER ' || OBJECT_TYPE || ' ' ||
   OWNER || '.' || OBJECT_NAME || ' COMPILE;'
from
   dba_objects
where
   status = 'INVALID'
and
   object_type in ('PACKAGE','FUNCTION','PROCEDURE','PACKAGE BODY')
and OWNER NOT LIKE ('MG%')
and owner not in('SYS','SYSTEM','WMSYS','BOCBS','DATUM','SYSMAN')
and owner||'.'||object_name not in
('GE.GE_INTERFAZ_APLICACION',            
'PA.PA_INT_GE_AGREGAGESTION',        
'SE.INFERDBUSER2',       
'SE.SE_SECURITYQUERIES_PKG',               
'SE.SE_INTERFASE_GN_REQUEST_PKG',                
'SE.SE_INTERFACE_GN_RESPONSE_PKG',            
'SE.SE_INTERFACE_GN_REQUEST_PKG',               
'SE.SE_INTERFACE_CS_RESPONSE_PKG',
'OGGMGR.DDLAUX',
'OGGMGR.CONTEO_PREPARACION_V2 COMPILE',
'TRADING.ONTR_MASSIVE_LOAD',
'OGGMGR.CONTEO_PREPARACION_V2 COMPILE',
'SE.SE_MONITORACTIVITY_PKG',
'SE.SE_PARAMETERS_PKG',
'SE.SE_INTERFACE_SCC_RESPONSE_PKG',
'SB.SB_INTC_GN',
'ENLACE.GN_INTC_UTILITIES',
'ENLACE.GN_INTA_NOTIFICATION',
'ENLACE.BO_AHORRO_PROGRAMADO',
'TD.TD_TARJETA',
'PSUITE.PMSG_INTERFAZ_CMPG',
'ORAPROBE.OSP_PACK');
/
